name: flutter_codes
description: "A Flutter component showcase application for developers."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_syntax_view: ^4.0.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_hooks: ^0.20.3
  iconsax: ^0.0.8
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/component_codes/
