name: flutter_codes
description: "A Flutter component showcase application for developers."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_syntax_view: ^4.0.0
  google_fonts: ^6.1.0
  flutter_hooks: ^0.21.2
  iconsax: ^0.0.8
  flutter_riverpod: ^2.6.1
  shimmer: ^3.0.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/component_codes/
    - assets/component_codes/appbar/
    - assets/component_codes/buttons/
    - assets/component_codes/carousels/
    - assets/component_codes/chips/
    - assets/component_codes/custom_shapes/
    - assets/component_codes/custom_shapes/containers/
    - assets/component_codes/custom_shapes/curved_edges/
    - assets/component_codes/definitions/
    - assets/component_codes/icons/
    - assets/component_codes/images/
    - assets/component_codes/image_text/
    - assets/component_codes/layouts/
    - assets/component_codes/list_tiles/
    - assets/component_codes/otp_input/
    - assets/component_codes/otp_textfield/
    - assets/component_codes/shimmers/
    - assets/component_codes/textfields/
    - assets/component_codes/texts/
    - assets/component_codes/views/
    - assets/windows/certificates/
    - assets/windows/licenses/

msix_config:
  publisher: CN=TopDevelopers
  display_name: Flutter Codes
  publisher_display_name: Top Developers
  identity_name: topdevelopers.fluttercode
  msix_version: 1.0.0.1
  languages: en-US
  enable_at_startup: true
  store: false
  install_certificate: false
  certificate_path: assets/windows/certificates/my_certificate.pfx
  certificate_password: FlutterCodes002
  logo_path: assets/images/logo.png
  licenses: assets/windows/licenses/DesktopLicense.xml
  capabilities: Music
  publish_folder_path: D:/FlutterCodesPublish
